### ISSUE TITLE
End Anchor in regex seems to have a strange behavior

### ISSUE THREAD

**Issue by mvoila** [intel/hyperscan#81] opened 2018-01-11 16:11 UTC
Hi,

I don't know if it is really an issue or if I misinterpreted the PCRE syntax but on patterns like the following I don't understand the result I got : 
^[1-9][0-9]{0,1} will match everything from '1' to '99'
[1-9][0-9]{0,1}$ will match nothing from '1' to '99'
^[1-9][0-9]{0,1}$ will match nothing from '1' to '99'

Is it normal?
Note : I used the expression '^[1-9][0-9]{0,1}$' in a PHP script for many years without any  issues.
Note 2 : Using HS v4.5.0 
Note 3 : Compilation done in block mode with only one pattern (same problem with 10+ patterns)

Anyway many thanks for hyperscan, it is an amazing tool !

Julien

**Comment by mdb256** [comment] 2018-01-12 00:37
Does the number appear at the end of the line, or at the end of the data you are passing to `hs_scan()`?

By default, ^ and $ match at the start and end of data, respectively - if you are trying to find matches at the start and end of line (`\n`), then you will need to call `hs_compile()` with the [HS_FLAG_MULTILINE](http://intel.github.io/hyperscan/dev-reference/api_constants.html#pattern-flags) flag.

For example, using `simplegrep`:
```
$ seq 1 99 > ninetynine
$ bin/simplegrep '[1-9][0-9]{0,1}$' ninetynine
Scanning 288 bytes with Hyperscan
Match for pattern "[1-9][0-9]{0,1}$" at offset 287
```
This is the final '99' in the file. If I change simplegrep.c to use multiline:
```diff
diff --git a/examples/simplegrep.c b/examples/simplegrep.c
index d6bd4b392..15ab7ed95 100644
--- a/examples/simplegrep.c
+++ b/examples/simplegrep.c
@@ -160,7 +160,7 @@ int main(int argc, char *argv[]) {
      */
     hs_database_t *database;
     hs_compile_error_t *compile_err;
-    if (hs_compile(pattern, HS_FLAG_DOTALL, HS_MODE_BLOCK, NULL, &database,
+    if (hs_compile(pattern, HS_FLAG_MULTILINE | HS_FLAG_DOTALL, HS_MODE_BLOCK, NULL, &database,
                    &compile_err) != HS_SUCCESS) {
         fprintf(stderr, "ERROR: Unable to compile pattern \"%s\": %s\n",
                 pattern, compile_err->message);
```
```
$ bin/simplegrep '[1-9][0-9]{0,1}$' ninetynine
Scanning 288 bytes with Hyperscan
Match for pattern "[1-9][0-9]{0,1}$" at offset 1
Match for pattern "[1-9][0-9]{0,1}$" at offset 3
Match for pattern "[1-9][0-9]{0,1}$" at offset 5
Match for pattern "[1-9][0-9]{0,1}$" at offset 7
[...]
Match for pattern "[1-9][0-9]{0,1}$" at offset 287
```
Which matches 1..99, one per line.

**Comment by mvoila** [comment] 2018-01-12 10:42
The number appears at the end of the data. In fact the data passed to hs_scan is only a number.
I use HS to recognize data type in documents. 

You may wonder why using anchors in patterns if I only pass the data.
When I was using PHP, I used simultaneously begin and end anchors to avoid sub matching.
When you pass '99' to scan, regex can match for '9' and '99'.
Am I wrong if I suppose that HS has the same behavior?

So when I scan a number without anything more [1-9][0-9]{0,1}$ and ^[1-9][0-9]{0,1}$ don't match. 
Do you observe the same behavior?

**Comment by mdb256** [comment] 2018-01-13 00:25
Absolutely this example should work.

Yes, without the anchors Hyperscan will return both matches at 9 and 99. Some other regular expression engines perform "greedy" matching, where they will return the longer of the matches, but HS semantics are to return all matches.

If we eliminate the trailing newline, it should behave the same:

```shell
$ echo -n 23 > twentythree
$ bin/simplegrep '^[1-9][0-9]{0,1}$' twentythree
Scanning 2 bytes with Hyperscan
Match for pattern "^[1-9][0-9]{0,1}$" at offset 2
$ bin/simplegrep '[1-9][0-9]{0,1}$' twentythree
Scanning 2 bytes with Hyperscan
Match for pattern "[1-9][0-9]{0,1}$" at offset 2
$ bin/simplegrep '^[1-9][0-9]{0,1}' twentythree
Scanning 2 bytes with Hyperscan
Match for pattern "^[1-9][0-9]{0,1}" at offset 1
Match for pattern "^[1-9][0-9]{0,1}" at offset 2
```
So unless something is happening to the pattern or data to be scanned on the way in to the HS API calls, I don't understand why your example would not work for you.

**Comment by mdb256** [comment] 2018-01-25 03:27
We have not been able to reproduce what you are seeing.

Closing the issue unless you can provide an example that matches the behaviour you describe.

**Closed by mdb256** 2018-01-25 03:27 UTC

**Comment by mvoila** [comment] 2018-04-03 08:32
Hi,

I'm back after some time.
After some investigations, hs_collide usage and valgrind headaches, i realized that hyperscan is not the problem but it's me.
I made a terrible mistake when I passed parameters to call hs_scan.
My original data is a std::string.
So when i would like to scan data with hyperscan i called str.c_str(); (suppose str is the variable's name).
For the data length to be scanned i passed sizeof(str.c_str()) which cause hyperscan to not scan two chars at the end.
Calling hs_scan with sizeof(str) works like a charm.

I apologize to annoy you with beginner's programming mistake.

Many thanks for this wonderfull software.
Where can i ask some questions (about performance and hardware ) which are not related to issues?

**Comment by xiangwang1** [comment] 2018-04-03 13:10
Hi,

It's good to hear that you have found the root cause. 
You can subscribe to our mailing list at https://lists.01.org/mailman/listinfo/hyperscan if you get any questions to ask.

**Comment by jviiret** [comment] 2018-04-04 01:49
Hi @mvoila,

> For the data length to be scanned i passed sizeof(str.c_str()) which cause hyperscan to not scan two chars at the end. Calling hs_scan with sizeof(str) works like a charm.

Just a small point: If you're using a `std::string` for your data, then probably what you want to use for the length parameter to `hs_scan()` is `str.length()`, which will pass the length of the string. Using `sizeof` will pass the length of the `std::string` object, rather than the length of the data it contains.
